name: Deploy to FTP

on:
  push:
    branches:
      - main

env:
  FTP_HOST: ${{ secrets.FTP_HOST }}
  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get committed files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.head_sha }} > committed-files.txt
          
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ env.FTP_HOST }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          server-dir: ${{ secrets.DEPLOY_DIR }}
          source: committed-files.txt
