name: Deploy to FTP

on:
  push:
    branches:
      - main

env:
  FTP_HOST: ${{ secrets.FTP_HOST }}
  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to FTP
      run: |
        set -ex
        COMMIT_HASH=$(git rev-parse HEAD)
        COMMIT_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_HASH)

        echo "Uploading the following files:"
        echo "$COMMIT_FILES"

        # Upload each committed file to the FTP server
        for FILE in $COMMIT_FILES; do
          curl -T $FILE ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST/$FILE
        done
